//! Host admission, permissions, and execution kernel.

mod config;
#[cfg_attr(
    test,
    allow(
        clippy::duplicate_mod,
        dead_code,
        reason = "execution test hooks are exercised by the integration-test harness, which also loads the module directly"
    )
)]
mod exec;
mod inspection;
mod jobs;
mod lifecycle;
mod role;
mod validate;

pub use inspection::{InspectError, Inspection, inspect};
pub use jobs::{DetachError, DetachedJobFailure, JobId};
pub use lifecycle::{
    Acceptance, AdmissionError, BudgetClass, EngineError, Host, HostBuilder, InvocationCtx,
    LimitSet, PluginConfig, PluginHandle, Prepared, RuntimeLimits, SymbolicRoots,
};
pub use lockgate_policy::{
    CapabilityContract, Permission, Scope, ScopeError, ScopeRepr, ScopedPermission, capability,
    check_scope_laws,
};

/// Generates typed application bindings for a WIT world.
///
/// For worlds with imported interfaces, the `data` option names the
/// [`CallContext`] type.
pub use lockgate_macros::host_bindings;
pub use role::{CallError, Role, RoleError, RoleInvocation, Value};
pub use validate::ValidationError;

/// The application value that travels with one plugin invocation — past the
/// plugin — from the host's call site to the host's import handlers.
///
/// The host sets it when invoking an export (the value given to
/// [`InvocationCtx::new`]) and reads it back inside its own generated import
/// implementations ([`HostCtx::data`]). The plugin in between can never
/// observe or forge it: it appears nowhere in the WIT and never enters guest
/// memory. That makes it the right carrier for facts about who a call is for —
/// the originating session, the requesting user — which import implementations
/// use to answer relative questions ("the current session") and to attribute
/// effects. It lives exactly as long as the invocation: supplied at the call,
/// dropped with the call's Store.
///
/// Any `Send + Sync + 'static` type qualifies through the blanket impl; never
/// implement this trait manually. Use `()` when calls carry no context.
pub trait CallContext: Send + Sync + 'static {}

impl<T: Send + Sync + 'static> CallContext for T {}

/// An application value whose generated host imports can be linked into a Store.
///
/// Implementations are generated by [`host_bindings!`]. Use `()` when plugins
/// do not import application functions. Lockgate clones this value into each
/// invocation Store, then clones that per-Store value for each host call so
/// overlapping guest calls are not serialized. Writes to ordinary, non-shared
/// fields are visible only within that host call and are discarded when it
/// returns, so later calls never observe them. Put intentionally shared state
/// in fields such as [`std::sync::Arc`].
pub trait HostImports<S>: Clone + Send + Sync + 'static {
    #[doc(hidden)]
    fn add_to_linker(
        &self,
        linker: &mut wasmtime::component::Linker<exec::StoreCtx<S>>,
    ) -> wasmtime::Result<()>;
}

impl HostImports<()> for () {
    fn add_to_linker(
        &self,
        _linker: &mut wasmtime::component::Linker<exec::StoreCtx<()>>,
    ) -> wasmtime::Result<()> {
        Ok(())
    }
}

/// Context supplied to every application host-import method.
#[derive(Clone)]
pub struct HostCtx<'a, S> {
    data: &'a S,
    plugin: &'a PluginHandle,
    jobs: jobs::DetachedJobContext,
}

impl<'a, S> HostCtx<'a, S> {
    #[doc(hidden)]
    pub fn new(data: &'a S, plugin: &'a PluginHandle, jobs: jobs::DetachedJobContext) -> Self {
        Self { data, plugin, jobs }
    }

    /// Returns the [call context](CallContext) for this invocation.
    pub fn data(&self) -> &S {
        self.data
    }

    /// Returns the plugin making this host call.
    pub fn plugin(&self) -> &PluginHandle {
        self.plugin
    }

    /// Detaches a host-owned future so it may outlive this invocation.
    ///
    /// Detached jobs have no Lockgate wall-clock deadline: the host capability
    /// owns their semantic lifetime. They are count-limited per admitted plugin
    /// and are aborted and awaited when the [`Host`] is dropped.
    pub fn detach<F, E>(&self, future: F) -> Result<JobId, DetachError>
    where
        F: std::future::Future<Output = Result<(), E>> + Send + 'static,
        E: Into<anyhow::Error> + Send + 'static,
    {
        self.jobs
            .detach(Box::pin(async move { future.await.map_err(Into::into) }))
    }
}

#[doc(hidden)]
pub mod __private {
    pub use crate::exec::StoreCtx;
    pub use crate::jobs::DetachedJobContext;
    pub use lockgate_policy;
    pub use wasmtime;
}

#[cfg(test)]
mod tests {
    use super::{exec::ExecEngine, jobs};

    #[test]
    fn creates_engine_with_pinned_configuration() {
        ExecEngine::new().expect("the pinned Wasmtime configuration should be valid");
    }

    #[tokio::test]
    async fn queued_detach_after_shutdown_is_aborted_and_awaited() {
        jobs::assert_queued_start_after_shutdown_is_aborted().await;
    }
}
