//! Host admission, permissions, and execution kernel.

#[cfg_attr(
    test,
    allow(
        dead_code,
        reason = "execution test hooks are exercised by the integration-test harness"
    )
)]
mod exec;
mod inspection;
mod lifecycle;
mod role;
mod validate;

pub use inspection::{InspectError, Inspection, inspect};
pub use lifecycle::{
    Acceptance, AdmissionError, BudgetClass, EngineError, Host, HostBuilder, InvocationCtx,
    LimitSet, PluginConfig, PluginHandle, Prepared, RuntimeLimits, SymbolicRoots,
};
pub use role::{CallError, Role, RoleError, RoleInvocation, Value};
pub use validate::ValidationError;

/// An application value whose generated host imports can be linked into a Store.
///
/// Implementations are generated by [`host_bindings!`]. Use `()` when plugins
/// do not import application functions.
pub trait HostImports<S>: Clone + Send + Sync + 'static {
    #[doc(hidden)]
    fn add_to_linker(
        &self,
        linker: &mut wasmtime::component::Linker<exec::StoreCtx<S>>,
    ) -> wasmtime::Result<()>;
}

impl<S> HostImports<S> for () {
    fn add_to_linker(
        &self,
        _linker: &mut wasmtime::component::Linker<exec::StoreCtx<S>>,
    ) -> wasmtime::Result<()> {
        Ok(())
    }
}

/// Context supplied to every application host-import method.
#[derive(Clone, Copy)]
pub struct HostCtx<'a, S> {
    data: &'a S,
    plugin: &'a PluginHandle,
}

impl<'a, S> HostCtx<'a, S> {
    #[doc(hidden)]
    pub fn new(data: &'a S, plugin: &'a PluginHandle) -> Self {
        Self { data, plugin }
    }

    /// Returns the application data for this invocation.
    pub fn data(&self) -> &S {
        self.data
    }

    /// Returns the plugin making this host call.
    pub fn plugin(&self) -> &PluginHandle {
        self.plugin
    }
}

#[doc(hidden)]
pub mod __private {
    pub use crate::exec::StoreCtx;
    pub use wasmtime;
}

#[cfg(test)]
mod tests {
    use super::exec::ExecEngine;

    #[test]
    fn creates_engine_with_pinned_configuration() {
        ExecEngine::new().expect("the pinned Wasmtime configuration should be valid");
    }
}
