//! Host admission, permissions, and execution kernel.

#[cfg(test)]
extern crate alloc;
#[cfg(test)]
extern crate self as lockgate;

mod config;
#[cfg(test)]
mod consent_tests;
#[cfg_attr(
    test,
    allow(
        clippy::duplicate_mod,
        dead_code,
        reason = "execution test hooks are exercised by the integration-test harness, which also loads the module directly"
    )
)]
mod exec;
#[cfg(test)]
mod http_tests;
mod inspection;
mod jobs;
mod lifecycle;
mod policy;
mod role;
mod validate;

pub use inspection::{InspectError, Inspection, inspect};
pub use jobs::{DetachError, DetachedJobFailure, JobId};
pub use lifecycle::{
    Acceptance, AdmissionError, BudgetClass, EngineError, Host, HostBuilder, HostConstructionError,
    InvocationCtx, LimitSet, PluginConfig, PluginHandle, Prepared, RuntimeLimits, SymbolicRoots,
};
pub use lockgate_policy::{
    CapabilityContract, HttpOrigin, Permission, Scope, ScopeError, ScopeRepr, ScopedPermission,
    capability, check_scope_laws, http,
};
pub use policy::{
    CapabilityRegistrationError, ConsentManifest, ConsentRecord, ConsentRequired, DriftChange,
    DriftKind, DriftReport, EffectiveGrants, GrantReview, HostImportPolicyError, InvalidScopeValue,
    JsonValueKind, NeedValueKind, PermissionDenied, PluginSubject, PreparedNeedsDigest, ResolveCtx,
    ResolveScopedResource, ResolveScopedResourceHandle, ResourceLookupError, ScopeReference,
    ScopeResolutionError, ScopedResource,
};
/// Typed handle used by generated host bindings for a WIT resource.
pub use wasmtime::component::Resource;

/// Generates typed application bindings for a WIT world.
///
/// For worlds with imported interfaces, the `data` option names the
/// [`CallContext`] type.
pub use lockgate_macros::{guarded, host_bindings, no_capability_required, requires};
pub use role::{CallError, Role, RoleError, RoleInvocation, Value};
pub use validate::ValidationError;

/// The application value that travels with one plugin invocation — past the
/// plugin — from the host's call site to the host's import handlers.
///
/// The host sets it when invoking an export (the value given to
/// [`InvocationCtx::new`]) and reads it back inside its own generated import
/// implementations ([`HostCtx::data`]). The plugin in between can never
/// observe or forge it: it appears nowhere in the WIT and never enters guest
/// memory. That makes it the right carrier for facts about who a call is for —
/// the originating session, the requesting user — which import implementations
/// use to answer relative questions ("the current session") and to attribute
/// effects. It lives exactly as long as the invocation: supplied at the call,
/// dropped with the call's Store.
///
/// Any `Send + Sync + 'static` type qualifies through the blanket impl; never
/// implement this trait manually. Use `()` when calls carry no context.
pub trait CallContext: Send + Sync + 'static {}

impl<T: Send + Sync + 'static> CallContext for T {}

/// An application value whose generated host imports can be linked into a Store.
///
/// Implementations are generated by [`host_bindings!`]; never implement this
/// trait manually. A handwritten implementation bypasses generated policy
/// metadata and selective wiring and is unsupported. Use `()` when plugins do
/// not import application functions.
///
/// Lockgate clones this value into each invocation Store, then clones that
/// per-Store value for each host call so overlapping guest calls are not
/// serialized. Writes to ordinary, non-shared fields are visible only within
/// that host call and are discarded when it returns, so later calls never
/// observe them. Put intentionally shared state in fields such as
/// [`std::sync::Arc`]. WIT resource representations are a deliberate
/// exception: Lockgate keeps those in a separate per-Store table and gives
/// guarded resource methods controlled access through [`ResolveCtx`].
pub trait HostImports<S>: Clone + Send + Sync + 'static {
    #[doc(hidden)]
    fn policy_metadata() -> Result<__private::HostImportPolicyMetadata, HostImportPolicyError>;

    #[doc(hidden)]
    fn add_to_linker(
        &self,
        linker: &mut wasmtime::component::Linker<exec::StoreCtx<S>>,
        interfaces: &[String],
    ) -> wasmtime::Result<()>;
}

impl HostImports<()> for () {
    fn policy_metadata() -> Result<__private::HostImportPolicyMetadata, HostImportPolicyError> {
        // `()` represents a world with no application imports, so empty
        // metadata is complete here rather than a policy-wiring bypass.
        Ok(__private::HostImportPolicyMetadata::__empty())
    }

    fn add_to_linker(
        &self,
        _linker: &mut wasmtime::component::Linker<exec::StoreCtx<()>>,
        _interfaces: &[String],
    ) -> wasmtime::Result<()> {
        Ok(())
    }
}

/// Context supplied to every application host-import method.
#[derive(Clone)]
pub struct HostCtx<'a, S> {
    data: &'a S,
    plugin: &'a PluginHandle,
    jobs: jobs::DetachedJobContext,
    resources: policy::ResourceStore,
}

impl<'a, S> HostCtx<'a, S> {
    #[doc(hidden)]
    pub fn new(
        data: &'a S,
        plugin: &'a PluginHandle,
        jobs: jobs::DetachedJobContext,
        resources: policy::ResourceStore,
    ) -> Self {
        Self {
            data,
            plugin,
            jobs,
            resources,
        }
    }

    /// Returns the [call context](CallContext) for this invocation.
    pub fn data(&self) -> &S {
        self.data
    }

    /// Returns the plugin making this host call.
    pub fn plugin(&self) -> &PluginHandle {
        self.plugin
    }

    /// Returns the stable policy subject for the plugin making this host call.
    pub fn subject(&self) -> PluginSubject<'_> {
        PluginSubject::new(self.plugin)
    }

    /// Returns the narrow context used for WIT resource resolution.
    ///
    /// It exposes the subject, immutable call data, and controlled operations
    /// on this invocation's resource table, but never effective grants.
    pub fn resolve_context(&self) -> ResolveCtx<'_, S> {
        ResolveCtx::new(self.data, self.plugin, &self.resources)
    }

    /// Requires one unscoped permission for this host call.
    pub fn require(&self, permission: Permission) -> Result<(), PermissionDenied> {
        let (capability, operation) = lockgate_policy::__private::permission_ids(permission);
        let atom = lockgate_schema::AtomKey::new(capability, operation)
            .expect("typed permissions always contain a valid wire atom");
        if self.plugin.effective_grants().has_unscoped(&atom) {
            Ok(())
        } else {
            Err(PermissionDenied::new(capability, operation))
        }
    }

    /// Requires one scoped permission to cover a resolved resource.
    pub fn require_scoped<T, R>(
        &self,
        permission: ScopedPermission<T>,
        resource: &R,
    ) -> Result<(), PermissionDenied>
    where
        T: Scope,
        <T as core::str::FromStr>::Err: Into<ScopeError>,
        R: ScopedResource<T> + ?Sized,
    {
        let (capability, operation) = lockgate_policy::__private::scoped_permission_ids(permission);
        let memberships = resource.scopes_for(&self.subject());
        if policy::scoped_access_allowed(
            self.plugin.capability_registry(),
            self.plugin.effective_grants(),
            permission,
            &memberships,
        ) {
            Ok(())
        } else {
            Err(PermissionDenied::new(capability, operation))
        }
    }

    /// Detaches a host-owned future so it may outlive this invocation.
    ///
    /// Detached jobs have no Lockgate wall-clock deadline: the host capability
    /// owns their semantic lifetime. They are count-limited per admitted plugin
    /// and are aborted and awaited when the [`Host`] is dropped.
    pub fn detach<F, E>(&self, future: F) -> Result<JobId, DetachError>
    where
        F: std::future::Future<Output = Result<(), E>> + Send + 'static,
        E: Into<anyhow::Error> + Send + 'static,
    {
        self.jobs
            .detach(Box::pin(async move { future.await.map_err(Into::into) }))
    }
}

#[doc(hidden)]
pub mod __private {
    pub use crate::exec::StoreCtx;
    pub use crate::jobs::DetachedJobContext;
    pub use crate::policy::{
        HostImportPolicyError, HostImportPolicyMetadata, InterfaceIdentity, MethodClassification,
        MethodIdentity, PolicyMethod, PolicyPermission, ResourceStore, ValidatedInterfacePolicy,
        resolve_scoped_resource, resolve_scoped_resource_handle, validate_interface_policy,
        validate_interface_policy_parts,
    };
    pub use lockgate_policy;
    pub use wasmtime;
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use lockgate_policy::ScopeRepr;
    use lockgate_schema::{AtomKey, GrantSet};

    use super::{
        HostCtx, PluginHandle, ScopedResource,
        exec::ExecEngine,
        jobs,
        policy::{CapabilityRegistry, EffectiveGrants, ResolvedNeeds, ResourceStore},
    };

    mod vm_contract {
        include!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../lockgate-policy/tests/fixtures/vm_contract.rs"
        ));
    }

    use vm_contract::permissions::vm::{self, InstanceScope};

    struct Vm {
        pool: &'static str,
    }

    impl ScopedResource<InstanceScope> for Vm {
        fn scopes_for(&self, _subject: &super::PluginSubject<'_>) -> Vec<InstanceScope> {
            vec![InstanceScope::Pool(self.pool.to_owned())]
        }
    }

    fn grants(unscoped: bool, scopes: &[InstanceScope]) -> EffectiveGrants {
        let mut required = GrantSet::new();
        if unscoped {
            required.insert_flag(AtomKey::new("vm", "list-pools").unwrap());
        }
        if !scopes.is_empty() {
            required
                .insert_scopes(
                    AtomKey::new("vm", "exec").unwrap(),
                    scopes.iter().map(ScopeRepr::canonical),
                )
                .unwrap();
        }
        EffectiveGrants::from_resolved(ResolvedNeeds {
            required,
            optional: GrantSet::new(),
        })
    }

    fn context(grants: EffectiveGrants) -> (PluginHandle, jobs::DetachedJobContext) {
        let mut registry = CapabilityRegistry::default();
        registry.register::<vm::Contract>().unwrap();
        let plugin = PluginHandle::for_policy_test_with_registry("plugin-a", grants, registry);
        let tracker = jobs::JobTracker::new().unwrap();
        let jobs = jobs::DetachedJobContext::new(Arc::clone(&tracker), "plugin-a".to_owned(), 1);
        (plugin, jobs)
    }

    #[test]
    fn creates_engine_with_pinned_configuration() {
        ExecEngine::new().expect("the pinned Wasmtime configuration should be valid");
    }

    #[test]
    fn host_context_enforces_unscoped_and_scoped_effective_grants() {
        let (plugin, jobs) = context(grants(true, &[InstanceScope::Pool("gpu".to_owned())]));
        let cx = HostCtx::new(&(), &plugin, jobs, ResourceStore::__new());

        assert_eq!(cx.subject().plugin_id(), "plugin-a");
        assert_eq!(cx.require(vm::LIST_POOLS), Ok(()));
        assert_eq!(cx.require_scoped(vm::EXEC, &Vm { pool: "gpu" }), Ok(()));
        let denial = cx
            .require_scoped(vm::EXEC, &Vm { pool: "cpu" })
            .unwrap_err();
        assert_eq!((denial.capability(), denial.permission()), ("vm", "exec"));
        assert_eq!(
            denial.to_string(),
            "permission `vm.exec` is not granted for this host call"
        );

        let (plugin, jobs) = context(grants(false, &[]));
        let cx = HostCtx::new(&(), &plugin, jobs, ResourceStore::__new());
        assert_eq!(
            cx.require(vm::LIST_POOLS).unwrap_err().permission(),
            "list-pools"
        );
    }

    #[tokio::test]
    async fn queued_detach_after_shutdown_is_aborted_and_awaited() {
        jobs::assert_queued_start_after_shutdown_is_aborted().await;
    }
}
