use std::{error::Error, fmt, time::Duration};

use wasmtime::component::Val;

use crate::CallContext;
use crate::exec::{ExecError, LoadedComponent};
use crate::lifecycle::{CallBudget, RegisteredCallBudgets, RuntimeLimits};

/// Converts a generated role's typed budget table into Lockgate's runtime form.
///
/// Implementations are generated by [`crate::host_bindings`].
#[doc(hidden)]
pub trait RoleBudgets: Sized {
    #[doc(hidden)]
    fn __into_entries(self) -> Vec<(&'static str, CallBudget)>;
}

impl RoleBudgets for () {
    fn __into_entries(self) -> Vec<(&'static str, CallBudget)> {
        Vec::new()
    }
}

/// A hand-written or generated view of one exported WIT interface.
///
/// Implementations name the interface and wrap the invocation capability in
/// their typed client. Generated clients and readable cast extensions use this
/// same trait.
pub trait Role: 'static {
    const INTERFACE: &'static str;

    type Budgets: RoleBudgets;

    type Client<'a, S>: 'a
    where
        S: CallContext,
        Self: 'a;

    fn client<'a, S>(invocation: RoleInvocation<'a, S>) -> Self::Client<'a, S>
    where
        S: CallContext;
}

/// Interface-scoped calling capability supplied to a role client at cast time.
pub struct RoleInvocation<'a, S: CallContext> {
    pub(crate) artifact: &'a LoadedComponent<S>,
    pub(crate) limits: RuntimeLimits,
    pub(crate) interface: &'static str,
    pub(crate) budgets: &'a RegisteredCallBudgets,
}

impl<S: CallContext> fmt::Debug for RoleInvocation<'_, S> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("RoleInvocation")
            .field("interface", &self.interface)
            .finish_non_exhaustive()
    }
}

impl<'a, S: CallContext> RoleInvocation<'a, S> {
    pub(crate) fn new(
        artifact: &'a LoadedComponent<S>,
        limits: RuntimeLimits,
        interface: &'static str,
        budgets: &'a RegisteredCallBudgets,
    ) -> Self {
        Self {
            artifact,
            limits,
            interface,
            budgets,
        }
    }

    /// Invokes one function in this role's interface using a fresh bounded Store.
    ///
    /// This is the narrow dynamic-value boundary for hand-written and generated
    /// role clients. Role clients lower their typed arguments to [`Value`]s and
    /// lift the returned values before exposing a typed method to applications.
    pub async fn invoke(
        &self,
        function: &str,
        arguments: &[Value],
        data: S,
    ) -> Result<Vec<Value>, CallError> {
        let budget = self.budgets.resolve(self.interface, function);
        self.invoke_with_budget(function, arguments, data, budget)
            .await
    }

    /// Invokes one function with a dynamic budget overriding its registered budget.
    pub async fn invoke_with_budget(
        &self,
        function: &str,
        arguments: &[Value],
        data: S,
        budget: CallBudget,
    ) -> Result<Vec<Value>, CallError> {
        budget
            .validate(format!("{}#{function}", self.interface))
            .map_err(|error| CallError::InvalidBudget {
                message: error.to_string(),
            })?;
        let export = self
            .artifact
            .export(self.interface, function)
            .ok_or_else(|| CallError::Dispatch {
                message: format!(
                    "interface `{}` has no function `{function}`",
                    self.interface
                ),
            })?;
        let CallBudget { fuel, deadline } = budget;
        self.artifact
            .invoke(export, arguments, data, self.limits.into(), fuel, deadline)
            .await
            .map_err(|error| CallError::from_exec(error, fuel))
    }
}

/// A dynamically lowered or lifted WIT value used inside role clients.
pub type Value = Val;

/// Failure of one plugin invocation.
#[derive(Debug)]
#[non_exhaustive]
pub enum CallError {
    /// The call's dynamic budget had a zero fuel or deadline bound.
    InvalidBudget { message: String },
    /// A fresh plugin instance could not be created for the call.
    Instantiate { message: String },
    /// Guest execution trapped.
    Trap { detail: String },
    /// The invocation exhausted its bounded fuel allowance.
    OutOfBudget { fuel: u64 },
    /// The invocation exceeded its bounded wall-clock allowance.
    DeadlineExceeded { deadline: Duration },
    /// A host import panicked while servicing the invocation.
    HostPanic { import: String, message: String },
    /// Dynamic function lookup, argument lowering, or result lifting failed.
    Dispatch { message: String },
}

impl CallError {
    /// Reports a mismatch while a role client lowers arguments or lifts results.
    pub fn shape(message: impl Into<String>) -> Self {
        Self::Dispatch {
            message: message.into(),
        }
    }

    fn from_exec(error: ExecError, fuel: u64) -> Self {
        match error {
            ExecError::Environment(error) => Self::Instantiate {
                message: error.to_string(),
            },
            ExecError::Instantiate(error) => Self::Instantiate {
                message: error.to_string(),
            },
            ExecError::Trap(detail) => Self::Trap {
                detail: detail.to_string(),
            },
            ExecError::OutOfBudget => Self::OutOfBudget { fuel },
            ExecError::DeadlineExceeded(deadline) => Self::DeadlineExceeded { deadline },
            ExecError::HostPanic { import, message } => Self::HostPanic { import, message },
            // Generated application imports currently use their outer failure
            // channel only for panics: WIT `result` values are guest data, while
            // only future fallible capability adapters can create HostImport.
            // A public host-import variant belongs here once capability adapters
            // can actually produce host-import failures.
            ExecError::HostImport(error) | ExecError::Dispatch(error) => Self::Dispatch {
                message: error.to_string(),
            },
        }
    }
}

impl fmt::Display for CallError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidBudget { message } => formatter.write_str(message),
            Self::Instantiate { message } => {
                write!(formatter, "plugin instance could not be created: {message}")
            }
            Self::Trap { detail } => write!(formatter, "plugin trapped: {detail}"),
            Self::OutOfBudget { fuel } => write!(
                formatter,
                "plugin exhausted its bounded call budget of {fuel} fuel units"
            ),
            Self::DeadlineExceeded { deadline } => write!(
                formatter,
                "plugin exceeded its bounded call deadline of {deadline:?}"
            ),
            Self::HostPanic { import, message } => {
                write!(formatter, "host import `{import}` panicked: {message}")
            }
            Self::Dispatch { message } => {
                write!(formatter, "plugin call could not be dispatched: {message}")
            }
        }
    }
}

impl Error for CallError {}

/// Failure to cast an admitted plugin handle to a role.
#[derive(Clone, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub enum RoleError {
    RoleNotExported { interface: &'static str },
    WrongHost,
}

impl fmt::Display for RoleError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::RoleNotExported { interface } => {
                write!(
                    formatter,
                    "plugin does not export role interface `{interface}`"
                )
            }
            Self::WrongHost => {
                formatter.write_str("plugin handle belongs to a different Lockgate Host")
            }
        }
    }
}

impl Error for RoleError {}
