[package]
name = "lockgate-plugin"
version.workspace = true
edition.workspace = true

[features]
default = ["runtime"]
runtime = ["dep:dlmalloc"]

[dependencies]
lockgate-plugin-macros = { path = "../lockgate-plugin-macros" }
schemars.workspace = true
serde = { workspace = true, default-features = false, features = ["alloc", "derive"] }
wit-bindgen = { workspace = true, default-features = false, features = ["async", "macros"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
dlmalloc = { version = "0.2", features = ["global"], optional = true }

[dev-dependencies]
lockgate-schema = { path = "../lockgate-schema" }
serde_json.workspace = true
