[package]
name = "lockgate-plugin"
version.workspace = true
edition.workspace = true

[dependencies]
lockgate-plugin-macros = { path = "../lockgate-plugin-macros" }
wit-bindgen = { workspace = true, default-features = false, features = ["macros"] }

[dev-dependencies]
lockgate-schema = { path = "../lockgate-schema" }
