[package]
name = "dynamic"
version = "0.1.0"
edition = "2024"

[dependencies]
wit-bindgen-rt = { version = "0.44.0", features = ["bitflags"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "demo:dynamic"

[package.metadata.component.target]
path = "wit"

[package.metadata.component.target.dependencies]
"tangent:core" = { path = "../../../../wit" }

[workspace]
