[package]
name = "lockgate-policy"
version.workspace = true
edition.workspace = true

[dependencies]
lockgate-macros = { version = "0.1.0", path = "../lockgate-macros" }
url.workspace = true

[dev-dependencies]
lockgate-schema = { version = "0.1.0", path = "../lockgate-schema" }
proptest = "1"
trybuild = "1"
