[package]
name = "lockgate"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1"
jsonschema = { version = "0.49.2", default-features = false }
lockgate-schema = { path = "../lockgate-schema" }
lockgate-macros = { path = "../lockgate-macros" }
lockgate-policy = { path = "../lockgate-policy" }
serde_json.workspace = true
sha2.workspace = true
tokio = { workspace = true, features = ["macros", "net", "rt", "sync", "time"] }
wasmparser.workspace = true
wasmtime.workspace = true
wasmtime-wasi.workspace = true
wasmtime-wasi-http.workspace = true
wit-parser.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }
trybuild = "1"
wasm-encoder.workspace = true
wit-component = { workspace = true, features = ["dummy-module"] }
wat.workspace = true
