[package]
name = "lockgate"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1"
lockgate-schema = { path = "../lockgate-schema" }
lockgate-macros = { path = "../lockgate-macros" }
serde_json.workspace = true
tokio = { workspace = true, features = ["macros", "net", "rt", "sync", "time"] }
wasmparser.workspace = true
wasmtime.workspace = true
wit-parser.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }
wasm-encoder.workspace = true
wit-component = { workspace = true, features = ["dummy-module"] }
wat.workspace = true
