[workspace]
resolver = "3"
members = [
    "exec-concurrent-guest",
    "exec-fuel-guest",
    "exec-guest",
]

[workspace.dependencies]
dlmalloc = { version = "0.2", features = ["global"] }
futures = { version = "0.3", default-features = false }
wit-bindgen = { version = "0.57", default-features = false }
