[workspace]
resolver = "3"
members = [
    "detached-jobs-guest",
    "exec-concurrent-guest",
    "exec-fuel-guest",
    "exec-guest",
    "host-bindings-guest",
    "public-guest",
    "renamed-facade",
    "renamed-host-facade",
]

[workspace.dependencies]
dlmalloc = { version = "0.2", features = ["global"] }
futures = { version = "0.3", default-features = false }
wit-bindgen = { version = "0.57", default-features = false }
