[package]
name = "lockgate-http-client-fixture"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
lockgate-http = { version = "0.1.0", path = "../../../../lockgate-http" }
lockgate-plugin = { version = "0.1.0", path = "../../../../lockgate-plugin", default-features = false }
