//! Typed application bindings used for catalog admission and runtime calls.

use crate::runtime::{PluginStore, RuntimeComponent};
use wasmtime::{
    Store,
    component::{Instance, Linker},
};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[doc(hidden)]
pub struct BindingExport {
    pub interface: &'static str,
    pub item: &'static str,
    pub signature: &'static str,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[doc(hidden)]
pub struct BindingImport {
    pub interface: &'static str,
}

/// A generated installer for one canonical application host interface.
#[doc(hidden)]
pub struct HostImportBinding<S: Send + 'static> {
    pub interface: &'static str,
    pub install: fn(&mut Linker<PluginStore<S>>) -> anyhow::Result<()>,
}

/// A generated application binding that describes and loads one component world's exports.
///
/// Implementations are generated by [`crate::bindings!`].
#[doc(hidden)]
pub trait ComponentBinding: Sized + 'static {
    const WORLD: &'static str;
    const EXPORTS: &'static [BindingExport];
    const IMPORTS: &'static [BindingImport] = &[];

    fn bind<H: Send + 'static>(
        store: &mut Store<PluginStore<H>>,
        instance: &Instance,
    ) -> anyhow::Result<Self>;
}

/// Host imports generated for an application binding and specialized to its state type.
#[doc(hidden)]
pub trait ApplicationBinding<S: Send + 'static>: ComponentBinding {
    fn host_imports() -> Vec<HostImportBinding<S>>;
}

/// A generated binding that can construct an ergonomic runtime client.
#[doc(hidden)]
pub trait RuntimeBinding<S: Send + 'static>: ComponentBinding {
    type Client<'runtime>
    where
        S: 'runtime;

    fn client<'runtime>(component: RuntimeComponent<'runtime, S, Self>) -> Self::Client<'runtime>
    where
        S: 'runtime;
}
