//! Typed application bindings used for catalog admission and runtime calls.

use crate::runtime::PluginStore;
use wasmtime::{Store, component::Instance};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[doc(hidden)]
pub struct BindingExport {
    pub interface: &'static str,
    pub item: &'static str,
    pub signature: &'static str,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[doc(hidden)]
pub struct BindingImport {
    pub interface: &'static str,
}

/// A generated application binding that describes and loads one component world's exports.
///
/// Implementations are generated by [`crate::bindgen!`].
#[doc(hidden)]
pub trait ComponentBinding: Sized + 'static {
    const WORLD: &'static str;
    const EXPORTS: &'static [BindingExport];
    const IMPORTS: &'static [BindingImport] = &[];

    fn bind<H: Send + 'static>(
        store: &mut Store<PluginStore<H>>,
        instance: &Instance,
    ) -> anyhow::Result<Self>;
}
