[package]
name = "lockgate-macros"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
heck.workspace = true
lockgate-schema = { path = "../lockgate-schema" }
proc-macro-crate.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
wasmtime-wit-bindgen.workspace = true
wit-parser.workspace = true

[dev-dependencies]
prettyplease = "0.2"
